### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by lovezm** [binux/qiandao#112]
Traceback (most recent call last):
  File "./run.py", line 42, in <module>
    PeriodicCallback(worker, config.check_task_loop, io_loop).start()
  File "/usr/local/lib/python2.7/dist-packages/tornado/ioloop.py", line 1209, in start
    self._schedule_next()
  File "/usr/local/lib/python2.7/dist-packages/tornado/ioloop.py", line 1237, in _schedule_next
    self._update_next(self.io_loop.time())
  File "/usr/local/lib/python2.7/dist-packages/tornado/ioloop.py", line 1244, in _update_next
    callback_time_sec *= 1 + (self.jitter * (random.random() - 0.5))
TypeError: unsupported operand type(s) for *: 'EPollIOLoop' and 'float'

**Comment by lovezm** [comment]
python2.7.9

**Comment by tao0ps** [comment]
同样的问题，如何解决？

**Comment by machsix** [comment]
I gave same issue here

**Comment by NoColor2** [comment]
I got the same

**Comment by CuteLuoBo** [comment]
同样情况，
Centos6.1-32bit,Python2.7.12

**Comment by Abiu1314** [comment]
me too

**Comment by shelterz** [comment]
tornado=4.5.3

**Comment by Abiu1314** [comment]
> tornado=4.5.3

感谢，已经完美解决

**Comment by CuteLuoBo** [comment]
> tornado=4.5.3

感谢，已经解决问题正常运行

**Comment by avrilnoeme** [comment]
`pip install tornado==4.5.3 u-msgpack-python jinja2 chardet requests pbkdf2 pycrypto`
