### ISSUE TITLE
编码问题求解 UnicodeDecodeError: 'utf8' codec can't decode byte 0x92 in position 0: invalid start byte

### ISSUE THREAD

**Issue by wfion** [binux/qiandao#125]
Traceback (most recent call last):
      File "/usr/local/python27/lib/python2.7/site-packages/tornado/web.py", line 1510, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/root/qiandao/web/handlers/login.py", line 33, in post
        if self.db.user.challenge(email, password):
      File "/root/qiandao/db/user.py", line 69, in challenge
        user = self.get(email=email, fields=('id', 'password'))
      File "/root/qiandao/db/user.py", line 126, in get
        for user in self._select2dic(what=fields, where=where, where_values=value):
      File "/root/qiandao/db/basedb.py", line 69, in _select2dic
        for row in dbcur:
      File "/usr/local/python27/lib/python2.7/site-packages/mysql/connector/cursor_cext.py", line 531, in fetchone
        row = self._cnx.get_row()
      File "/usr/local/python27/lib/python2.7/site-packages/mysql/connector/connection_cext.py", line 306, in get_row
        raw=raw)
      File "/usr/local/python27/lib/python2.7/site-packages/mysql/connector/connection_cext.py", line 276, in get_rows
        row = self._cmysql.fetch_row()
      File "/usr/local/python27/lib/python2.7/encodings/utf_8.py", line 16, in decode
        return codecs.utf_8_decode(input, errors, True)
    UnicodeDecodeError: 'utf8' codec can't decode byte 0x92 in position 0: invalid start byte

我发誓 我就改了config文件其他的我都没碰

[![TIM图片20190225130651](https://i.loli.net/2019/02/25/5c73784802e30.png)](https://i.loli.net/2019/02/25/5c73784802e30.png)

**Comment by niguolaiya** [comment]
同问。。。注册后登出再登陆就 500了，，去查看也是显示这个
