### ISSUE TITLE
MySQL pool exhausted

### ISSUE THREAD

**Issue by legendtang** [binux/qiandao#33]
```
Traceback (most recent call last):
  File ".\run.py", line 40, in <module>
    worker = MainWorker()
  File "E:\github\qiandao\worker.py", line 29, in __init__
    class DB(object):
  File "E:\github\qiandao\worker.py", line 30, in DB
    user = db.UserDB()
  File "E:\github\qiandao\db\user.py", line 34, in __init__
    database=database, autocommit=True, pool_size=5)
  File "D:\Python27\lib\site-packages\mysql\connector\__init__.py", line 163, in connect
    return _get_pooled_connection(**kwargs)
  File "D:\Python27\lib\site-packages\mysql\connector\__init__.py", line 79, in _get_pooled_connection
    return _CONNECTION_POOLS[pool_name].get_connection()
  File "D:\Python27\lib\site-packages\mysql\connector\pooling.py", line 310, in get_connection
    "Failed getting connection; pool exhausted")
mysql.connector.errors.PoolError: Failed getting connection; pool exhausted
```

Using Latest commit `15909f7`. The MySQL shows process list as follow:
```
MariaDB [qiandao]> show processlist;
+----+------+-----------------+---------+---------+------+-------+------------------+----------+
| Id | User | Host            | db      | Command | Time | State | Info             | Progress |
+----+------+-----------------+---------+---------+------+-------+------------------+----------+
| 15 | root | localhost:34299 | qiandao | Query   |    0 | init  | show processlist |    0.000 |
| 16 | root | localhost:34358 | qiandao | Sleep   |    5 |       | NULL             |    0.000 |
| 17 | root | localhost:34359 | qiandao | Sleep   |    5 |       | NULL             |    0.000 |
| 18 | root | localhost:34360 | qiandao | Sleep   |    5 |       | NULL             |    0.000 |
| 19 | root | localhost:34361 | qiandao | Sleep   |    5 |       | NULL             |    0.000 |
| 20 | root | localhost:34362 | qiandao | Sleep   |    5 |       | NULL             |    0.000 |
+----+------+-----------------+---------+---------+------+-------+------------------+----------+
6 rows in set (0.00 sec)
```

**Comment by legendtang** [comment]
I think the issue is resolved by https://github.com/binux/qiandao/commit/f010307a63494feca52b965654f9362cae9d547e.
