### ISSUE TITLE
导入模板后字符编解码出错

### ISSUE THREAD

**Issue by kun945** [binux/qiandao#34]
OS：
```
Linux lemaker 3.4.103 #1 SMP PREEMPT Thu Dec 18 13:07:12 CST 2014 armv7l GNU/Linux
```

python：
```
Python 2.7.3 32bit
```

错误信息:
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1467, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1726, in wrapper
    return method(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 2829, in wrapper
    return method(self, *args, **kwargs)
  File "/home/bananapi/sources/qiandao/web/handlers/my.py", line 34, in get
    self.render('my.html', tpls=tpls, tasks=tasks, my_status=my_status)
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 719, in render
    html = self.render_string(template_name, **kwargs)
  File "/home/bananapi/sources/qiandao/web/handlers/base.py", line 48, in render_string
    return template.render(namespace)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/bananapi/sources/qiandao/web/tpl/my.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/bananapi/sources/qiandao/web/tpl/base.html", line 35, in top-level template code
    {% block body %}{% endblock %}
  File "/home/bananapi/sources/qiandao/web/tpl/my.html", line 90, in block "body"
    {{ utils.tplname(tpl) }}
  File "/home/bananapi/sources/qiandao/web/tpl/utils.html", line 100, in template
    <span data-toggle="popover" data-content="{{ tpl.siteurl }}">{{ tpl.sitename or "未命名" }}</span>
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128)
```

导入模板后用中文命名网站名字，出现这样的错误。

**Comment by binux** [comment]
你用的什么数据库？mysql 还是 sqlite？

**Comment by kun945** [comment]
@binux  用的是sqlite

**Comment by xuexiaokang** [comment]
我也是这个错误
