### ISSUE TITLE
Both web and lite versions cannot work

### ISSUE THREAD

**Issue by weakish** [binux/qiandao#41]
When submitting task (v2ex) on web, a.k.a `run.py`:

```python
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/tornado/web.py", line 1141, in _when_complete
    callback()
  File "/usr/lib/python2.7/dist-packages/tornado/web.py", line 1162, in _execute_method
    self._when_complete(method(*self.path_args, **self.path_kwargs),
  File "/usr/lib/python2.7/dist-packages/tornado/web.py", line 2297, in wrapper
    return method(self, *args, **kwargs)
  File "/pool/repos/forks/qiandao/web/handlers/task.py", line 42, in post
    tplid = int(self.get_body_argument('_binux_tplid'))
  File "/pool/repos/forks/qiandao/web/handlers/base.py", line 27, in __getattr__
    raise AttributeError('no such attr: %s' % key)
AttributeError: no such attr: get_body_argument
```

Lite version also does not work:

```sh
; python qiandao.py huihui.har --username=xxx --password=xxx
```

Got:

```python
ERROR:root:__init__() got an unexpected keyword argument 'decompress_response' 
Traceback (most recent call last):
  File "/pool/repos/forks/qiandao/libs/fetcher.py", line 445, in do_fetch
    ), proxy=proxy)
  File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 496, in run
    next = self.yield_point.get_result()
  File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 395, in get_result
    return self.runner.pop_result(self.key).result()
  File "/usr/lib/python2.7/dist-packages/tornado/concurrent.py", line 129, in result
    raise_exc_info(self.__exc_info)
  File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 221, in wrapper
    runner.run()
  File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 507, in run
    yielded = self.gen.send(next)
  File "/pool/repos/forks/qiandao/libs/fetcher.py", line 359, in fetch
    req, rule, env = self.build_request(obj, self.download_size_limit)
  File "/pool/repos/forks/qiandao/libs/fetcher.py", line 99, in build_request
    prepare_curl_callback = set_size_limit_callback,
TypeError: __init__() got an unexpected keyword argument 'decompress_response'
qiandao failed! failed at 1/1 request, error:TypeError("__init__() got an unexpected keyword argument 'decompress_response'",), https://reg.163.com/logins.jsp
```

**Comment by binux** [comment]
升级 tornado 版本
