### ISSUE TITLE
搭建好了 为什么一保存就出错？

### ISSUE THREAD

**Issue by Mathisdifficult** [binux/qiandao#43]
搭建好网站后 #python web.py ,进入ip:8923上传HAR,测试什么的都是成功的，但是保存的时候提示Traceback (most recent call last): File "/usr/local/lib/python2.7/site-packages/tornado/web.py", line 1467, in _execute result = method(*self.path_args, **self.path_kwargs) File "/root/qiandao-master/web/handlers/har.py", line 28, in post tpl['har'] = self.db.user.decrypt(tpl['userid'], tpl['har']) File "/root/qiandao-master/db/user.py", line 112, in decrypt raise self.UserDBException('decrypt error') UserDBException: decrypt error。
再次返回到首页 提示Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/tornado/web.py", line 1467, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/usr/local/lib/python2.7/site-packages/tornado/web.py", line 1726, in wrapper
    return method(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/tornado/web.py", line 2829, in wrapper
    return method(self, *args, **kwargs)
  File "/root/qiandao-master/web/handlers/my.py", line 34, in get
    self.render('my.html', tpls=tpls, tasks=tasks, my_status=my_status)
  File "/usr/local/lib/python2.7/site-packages/tornado/web.py", line 719, in render
    html = self.render_string(template_name, **kwargs)
  File "/root/qiandao-master/web/handlers/base.py", line 48, in render_string
    return template.render(namespace)
  File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/root/qiandao-master/web/tpl/my.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/root/qiandao-master/web/tpl/base.html", line 35, in top-level template code
    {% block body %}{% endblock %}
  File "/root/qiandao-master/web/tpl/my.html", line 90, in block "body"
    {{ utils.tplname(tpl) }}
  File "/root/qiandao-master/web/tpl/utils.html", line 98, in template
    <span data-toggle="popover" title="{{ tpl.siteurl }}" data-content="{{ tpl.note }}">{{ tpl.sitename or "鏈懡鍚�" }}</span>
UnicodeDecodeError: 'ascii' codec can't decode byte 0xfd in position 0: ordinal not in range(128)

**Comment by binux** [comment]
1. 你是不是本地访问，没有登录
2. sitename 别带中文

**Comment by xuexiaokang** [comment]
我一保存的错误是Traceback (most recent call last): File "/usr/lib/python2.6/site-packages/tornado/web.py", line 1467, in _execute result = method(*self.path_args, **self.path_kwargs) File "/home/wwwroot/qiandaotoday/web/qiandao/web/handlers/har.py", line 28, in post tpl['har'] = self.db.user.decrypt(tpl['userid'], tpl['har']) File "/home/wwwroot/qiandaotoday/web/qiandao/db/user.py", line 112, in decrypt raise self.UserDBException('decrypt error') UserDBException: decrypt error
