### ISSUE TITLE
如何指定使用mysql或者sqlite3？ 编码出问题了

### ISSUE THREAD

**Issue by ShinonomeHana** [binux/qiandao#44]
实在不好意思了，因为使用介绍写的实在是简略到获取不了任何可用信息的地步了
所以才来发issue
比如我vps上同时安装了mysql和sqlite3.框架是默认使用哪个？
然后我如果想指定使用另外一个数据库该怎么做？

现在看的话默认使用的是sqlite3？如果我想用mysql的话该怎么指定？

然后现在默认使用sqlite3的情况下有编码问题
看py提示和别人的issue似乎是sitename的问题？但我找了半天都不知道这sitename去哪里设置…………
然后之前导入有中文的模板后也有编码问题，最后没办法是直接清空数据库重搞才解决。

> Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1467, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1726, in wrapper
    return method(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 2829, in wrapper
    return method(self, *args, **kwargs)
  File "/root/qiandao/web/handlers/my.py", line 34, in get
    self.render('my.html', tpls=tpls, tasks=tasks, my_status=my_status)
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 719, in render
    html = self.render_string(template_name, **kwargs)
  File "/root/qiandao/web/handlers/base.py", line 48, in render_string
    return template.render(namespace)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/root/qiandao/web/tpl/my.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/root/qiandao/web/tpl/base.html", line 35, in top-level template code
    {% block body %}{% endblock %}
  File "/root/qiandao/web/tpl/my.html", line 90, in block "body"
    {{ utils.tplname(tpl) }}
  File "/root/qiandao/web/tpl/utils.html", line 98, in template
    <span data-toggle="popover" title="{{ tpl.siteurl }}" data-content="{{ tpl.note }}">{{ tpl.sitename or "未命名" }}</span>
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128)

**Comment by binux** [comment]
https://github.com/binux/qiandao/blob/master/config.py#L31
sqlite 不是 qiandao.today 用的数据库，可能会有 bug

**Comment by ShinonomeHana** [comment]
原来如此，直接在脚本里改，都没看脚本代码，哈哈
这样的确就能用mysql，管理起来也方便了，谢谢作者！
