### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by ShmilyChen** [binux/qiandao#90]
运行./run.py后控制台报错
Traceback (most recent call last):
  File "./run.py", line 42, in <module>
    PeriodicCallback(worker, config.check_task_loop, io_loop).start()
TypeError: __init__() takes exactly 3 arguments (4 given)

**Comment by dnvcupid** [comment]
我也是这样，同求怎么解决

**Comment by binux** [comment]
降级tornado

**Comment by dnvcupid** [comment]
tornado 要什么版本吗

**Comment by dnvcupid** [comment]
大佬什么时候抽空更新一下代码呗

**Comment by dnvcupid** [comment]
再顺便问问这个`RequestsDependencyWarning: urllib3 (1.22) or chardet (2.3.0) doesn't match a supported version! `，这个也是版本问题吗，需要什么版本，tornado 用4.5.3可以解决下面这个问题`Traceback (most recent call last):
File "./run.py", line 42, in 
PeriodicCallback(worker, config.check_task_loop, io_loop).start()
TypeError: init() takes exactly 3 arguments (4 given)`

**Comment by xinghusp** [comment]
使用pip install tornado==4.5.3 降级tornado就可以用了
